### PR TITLE
Mark SCP-027 as dormant

### PR DESCRIPTION
**Pull request by julienrf**
After the proposal was accepted by the board members, the Scala Center created a working group to explore its feasibility and propose a concrete technical solution. We published the results of the working group in #101.

We don’t plan to work more on the proposal anytime soon as we did not perceive much interest from the community or the stakeholders. We believe our resources are better spent on other tasks, as shown in our [roadmap](https://www.scala-lang.org/blog/2023/01/31/scala-center-2023-roadmap.html).

### CODE REVIEW

**Comment by SethTisue** [comment]
as also discussed at there board meeting yesterday.

**Comment by SethTisue** [comment]
#125 includes the updated README

**Comment by ckipp01** [comment]
Wait, from my understanding we were going to wait another month and gather feedback before marking this as dormant?

**Comment by SethTisue** [comment]
um, hmm, not sure

for now, c30fe74ccbbd19157700078b81ca44cb05f3f567 reverts this PR

I'll either include the changes, or not, in #125, after I've reviewed the meeting video

**Comment by ckipp01** [comment]
> after I've reviewed the meeting video

Which was the reminder I needed to share it with you 😆 Just did that.

**Pull request merged**
