### PR TITLE
update proposal statuses and add SCP-021 and SCP-022

### PR DESCRIPTION
**Pull request by SethTisue**
I'm not sure if SCP-020 should be considered active or dormant? it wasn't mentioned at the December 2019 meeting, I don't think

### CODE REVIEW

**Comment by julienrf** [comment]
Hey @SethTisue , thanks for the update :)

I believe SCP-020 is completed. The three actionable points of the proposal have all been implemented (documentation on dependencies management, conflict managers improvements, and sbt-missinglink). What do you think?

**Comment by SethTisue** [comment]
I think whatever @sjrd thinks :-)

it's one I really haven't followed

**Comment by sjrd** [comment]
Yes, I consider 020 complete. There are usability issues in sbt-missinglink that we should address, but that's basically maintenance. The proposal itself has been addressed.

**Comment by dwijnand** [comment]
> documentation on dependencies management, conflict managers improvements, and sbt-missinglink

I know where sbt-missinglink is.  Where can I find the resulting documentation and improvements?

**Comment by sjrd** [comment]
There are pointers from [here](https://www.scala-lang.org/2019/10/17/dependency-management.html) to everywhere.

**Comment by sjrd** [comment]
Thanks @SethTisue !

**Pull request merged**
