### PR TITLE
add SCP-031: Ensure reachability of Scala websites

### PR DESCRIPTION
**Pull request by SethTisue**
review by @julienrf, @ckipp01, @lrytz, @darjutak ?

### CODE REVIEW

**Review by ckipp01 — APPROVED** [review]
This is a big LGTM from me.

**Review by julienrf — APPROVED** [review]

**Review by lrytz — APPROVED** [review]

**Review by darjutak — APPROVED** [review]

**Comment by ckipp01** [comment]
I'll go ahead and merge, and I'll make sure this gets on the agenda for the upcoming meeting.

**Comment by SethTisue** [comment]
looks like Fabian finished this up, so the proposal is now moot: https://github.com/scala/scala-lang/issues/1456#issuecomment-1630464834

**Comment by SethTisue** [comment]
#133 marks the proposal as both accepted and completed. (At the board meeting last week, nobody objected to considering
it “accepted” even though it was completed before the board got a chance to vote on it.)

**Pull request merged**
